package com.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.io.Serializable;

/**
 * Created by Niharp on 11/24/2017.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Listing{
    private Long id;
    private String name;
    private String summary;
    private String space;
    private Address address;
    private PropertyInfo propertyInfo;
    private String city;
    private String descriptor;
    private String location;
    private Long zipCode;

}
